 
#define   LED_PIN              11
#define   TURN_LEFT_PIN        2
#define   STOP_PIN             6
#define   TURN_RIGHT_PIN       4


#define   TURN_LEFT_PIXEL_NUM              29 //кол-во LED на левый поворот
#define   TURN_RIGHT_PIXEL_NUM             TURN_LEFT_PIXEL_NUM //кол-во LED на правый поворот
#define   STOP_PIXEL_NUM                   (TURN_LEFT_PIXEL_NUM + TURN_RIGHT_PIXEL_NUM)//58 //кол-во LED на стоп
#define   SIDE_PIXEL_NUM                   STOP_PIXEL_NUM//58 //кол-во LED на габариты
#define   TURN_RIGHT_INDICATOR_PIXEL_NUM   0
#define   TURN_LEFT_INDICATOR_PIXEL_NUM    0
#define   STOP_INDICATOR_PIXEL_NUM         0
#define   PIXEL_NUM                        (TURN_RIGHT_INDICATOR_PIXEL_NUM + TURN_LEFT_INDICATOR_PIXEL_NUM + \
                                            STOP_INDICATOR_PIXEL_NUM + TURN_LEFT_PIXEL_NUM + TURN_RIGHT_PIXEL_NUM)//58


//начальные LED
#define   TURN_LEFT_INDICATOR_START   (STOP_INDICATOR_START + STOP_INDICATOR_PIXEL_NUM)//0
#define   TURN_RIGHT_INDICATOR_START  0
#define   STOP_INDICATOR_START        (TURN_RIGHT_INDICATOR_START + TURN_RIGHT_INDICATOR_PIXEL_NUM)//1
#define   TURN_LEFT_PIXEL_START       (TURN_LEFT_INDICATOR_START + TURN_LEFT_INDICATOR_PIXEL_NUM)//3
#define   TURN_RIGHT_PIXEL_START      (TURN_LEFT_PIXEL_START + TURN_LEFT_PIXEL_NUM)
#define   STOP_PIXEL_START            TURN_LEFT_PIXEL_START//3
#define   SIDE_PIXEL_START            TURN_LEFT_PIXEL_START//3

#define   TURN_PICTURE_NUM     29
#define   STOP_PICTURE_NUM     2
#define   SIDE_PICTURE_NUM     1

#define   TURN_SHOW_DELAY      60
#define   STOP_SHOW_DELAY      180
#define   SIDE_SHOW_DELAY      5

#define   TURN_BACKGROUND      ((uint32_t) 0x000A0000)
#define   STOP_BACKGROUND      ((uint32_t) 0x000A0000)
#define   STOP_ACTIVE_COLOR    ((uint32_t) 0x05FF0000)
#define   STOP_ACTIVE_COLOR2   ((uint32_t) 0x025F0000)
#define   TURN_INDICATOR_COLOR ((uint32_t) 0xFFFFF000) 
#define   STOP_INDICATOR_COLOR ((uint32_t) 0x00F00000) 


#define   TURN_RESET           0
#define   TURN_ON              1
#define   TURN_OFF             2

#define   TURN_INDICATOR_BLINK_VALUE      5 //время = TURN_SHOW_DELAY * TURN_BLINK_RATE
#define   TURN_INDICATOR_PHASE_OFF        0
#define   TURN_INDICATOR_PHASE_ON         1

//поворот
const uint32_t Picture_1[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};
const uint32_t Picture_2[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_3[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_4[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_5[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_6[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_7[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};
const uint32_t Picture_8[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};
const uint32_t Picture_9[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_10[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_11[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_12[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_13[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_14[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_15[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_16[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_17[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};

const uint32_t Picture_18[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_19[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_20[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_BACKGROUND, 
};

const uint32_t Picture_21[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
};

const uint32_t Picture_22[] PROGMEM = //.....................................
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
};

const uint32_t Picture_23[] PROGMEM = //....................................
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
};



//..................................поворот + стоп
const uint32_t Picture_24[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_25[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_26[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_27[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_28[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_29[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_30[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };
const uint32_t Picture_31[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };
const uint32_t Picture_32[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_33[] PROGMEM = 
{ 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_34[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_35[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_36[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_37[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_38[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_39[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_40[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_41[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_42[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_43[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_44[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, STOP_ACTIVE_COLOR, 
  };

const uint32_t Picture_45[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_46[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_47[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_48[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_49[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_50[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_51[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_52[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_53[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_54[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_55[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

  const uint32_t Picture_56[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_57[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_58[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_59[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_60[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_61[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
   };

const uint32_t Picture_62[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_63[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_64[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_65[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_66[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_67[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };

const uint32_t Picture_68[] PROGMEM = 
{
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, TURN_INDICATOR_COLOR, 
  };


//Stop
const uint32_t Picture_69[] PROGMEM = 
{
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR,
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR,
};

const uint32_t Picture_70[] PROGMEM = 
{
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2,
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, 
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, 
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2,
};

//BACKGROUND
const uint32_t Picture_71[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};
