 
#define   LED_PIN              11
#define   TURN_LEFT_PIN        2
#define   STOP_PIN             6
#define   TURN_RIGHT_PIN       4


#define   TURN_LEFT_PIXEL_NUM              13 //кол-во LED на левый поворот
#define   TURN_RIGHT_PIXEL_NUM             TURN_LEFT_PIXEL_NUM //кол-во LED на правый поворот
#define   STOP_PIXEL_NUM                   (TURN_LEFT_PIXEL_NUM + TURN_RIGHT_PIXEL_NUM)//16 //кол-во LED на стоп
#define   SIDE_PIXEL_NUM                   STOP_PIXEL_NUM//16 //кол-во LED на габариты
#define   TURN_RIGHT_INDICATOR_PIXEL_NUM   3
#define   TURN_LEFT_INDICATOR_PIXEL_NUM    3
#define   STOP_INDICATOR_PIXEL_NUM         2
#define   PIXEL_NUM                        (TURN_RIGHT_INDICATOR_PIXEL_NUM + TURN_LEFT_INDICATOR_PIXEL_NUM + \
                                            STOP_INDICATOR_PIXEL_NUM + TURN_LEFT_PIXEL_NUM + TURN_RIGHT_PIXEL_NUM)//19


//начальные LED
#define   TURN_LEFT_INDICATOR_START   (STOP_INDICATOR_START + STOP_INDICATOR_PIXEL_NUM)//2
#define   TURN_RIGHT_INDICATOR_START  0
#define   STOP_INDICATOR_START        (TURN_RIGHT_INDICATOR_START + TURN_RIGHT_INDICATOR_PIXEL_NUM)//1
#define   TURN_LEFT_PIXEL_START       (TURN_LEFT_INDICATOR_START + TURN_LEFT_INDICATOR_PIXEL_NUM)//3
#define   TURN_RIGHT_PIXEL_START      (TURN_LEFT_PIXEL_START + TURN_LEFT_PIXEL_NUM)
#define   STOP_PIXEL_START            TURN_LEFT_PIXEL_START//3
#define   SIDE_PIXEL_START            TURN_LEFT_PIXEL_START//3

#define   TURN_PICTURE_NUM     99
#define   STOP_PICTURE_NUM     2
#define   SIDE_PICTURE_NUM     1

#define   TURN_SHOW_DELAY      30
#define   STOP_SHOW_DELAY      180
#define   SIDE_SHOW_DELAY      5

#define   TURN_BACKGROUND      ((uint32_t) 0x00010000)
#define   STOP_BACKGROUND      ((uint32_t) 0x00050000)
#define   STOP_ACTIVE_COLOR    ((uint32_t) 0x05FF0000)
#define   STOP_ACTIVE_COLOR2   ((uint32_t) 0x025F0000)
#define   TURN_ACTIVE_COLOR    ((uint32_t) 0x03591300)
#define   TURN_INDICATOR_COLOR ((uint32_t) 0x00090300) 
#define   STOP_INDICATOR_COLOR ((uint32_t) 0x00100000) 


#define   TURN_RESET           0
#define   TURN_ON              1
#define   TURN_OFF             2

#define   TURN_INDICATOR_BLINK_VALUE      5 //время = TURN_SHOW_DELAY * TURN_BLINK_RATE
#define   TURN_INDICATOR_PHASE_OFF        0
#define   TURN_INDICATOR_PHASE_ON         1

//поворот
const uint32_t Picture_1[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};
const uint32_t Picture_2[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};

const uint32_t Picture_3[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};

const uint32_t Picture_4[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_5[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_6[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_7[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};
const uint32_t Picture_8[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
};
const uint32_t Picture_9[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};

const uint32_t Picture_10[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};

const uint32_t Picture_11[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
};

const uint32_t Picture_12[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
};

const uint32_t Picture_13[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_14[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_15[] PROGMEM =  
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_16[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_17[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_18[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_ACTIVE_COLOR,   
};

const uint32_t Picture_19[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_20[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_21[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_22[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_23[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_24[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_25[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_26[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_27[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_28[] PROGMEM = //....................................
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_29[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};
const uint32_t Picture_30[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_31[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_32[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_33[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_34[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_35[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_36[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_37[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_38[] PROGMEM = //....................................
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_39[] PROGMEM = //....................................
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_40[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_41[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_42[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_43[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_44[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_45[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_46[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_47[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_48[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_49[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_50[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_51[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_52[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_53[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_54[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_55[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_56[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_57[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_58[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_59[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_60[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_61[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_62[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_63[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_64[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_65[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_66[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_67[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_68[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_69[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_70[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_71[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_72[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_73[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_74[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_75[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR,  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_76[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_77[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_78[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_79[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_80[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_81[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_82[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_83[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_84[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_85[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_86[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_87[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_88[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_89[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_90[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_91[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_92[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_93[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_94[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_95[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,  
};

////..................................поворот + стоп......................................................................................................................
const uint32_t Picture_96[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};
const uint32_t Picture_97[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};

const uint32_t Picture_98[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};

const uint32_t Picture_99[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
};

const uint32_t Picture_100[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
};

const uint32_t Picture_101[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
};

const uint32_t Picture_102[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
};
const uint32_t Picture_103[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
};
const uint32_t Picture_104[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};

const uint32_t Picture_105[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};

const uint32_t Picture_106[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
};

const uint32_t Picture_107[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
};

const uint32_t Picture_108[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_109[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_110[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_111[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_112[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_113[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  STOP_BACKGROUND, TURN_ACTIVE_COLOR,   
};

const uint32_t Picture_114[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_115[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,  
};

const uint32_t Picture_116[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
};

const uint32_t Picture_117[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_118[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_119[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_120[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_121[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_122[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_123[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_124[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};
const uint32_t Picture_125[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_126[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_127[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_128[] PROGMEM = //....................................
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_129[] PROGMEM = //....................................
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_130[] PROGMEM = //....................................
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_131[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_132[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_133[] PROGMEM = //....................................
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_134[] PROGMEM = //....................................
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_135[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_136[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_137[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_138[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_139[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_140[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_141[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_142[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_143[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_144[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_145[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_146[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_147[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_148[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_149[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_150[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_151[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_152[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_153[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_154[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_155[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_156[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_157[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_158[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_159[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_160[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_161[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_162[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_163[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_164[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND,  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_165[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND,  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_166[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND,  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_167[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND,  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_168[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND,  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_169[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR,  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_170[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR,  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_171[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_172[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_173[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_174[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_175[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_176[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_177[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_178[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_179[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_180[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_181[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_182[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_183[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_184[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_185[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_186[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_187[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_188[] PROGMEM = 
{
  STOP_BACKGROUND, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_189[] PROGMEM = 
{
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, 
  TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR, TURN_ACTIVE_COLOR,
};

const uint32_t Picture_190[] PROGMEM = 
{
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, 
  STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND, STOP_BACKGROUND,  
};


//Stop
const uint32_t Picture_191[] PROGMEM = 
{
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR,
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, 
  STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR, STOP_ACTIVE_COLOR,
};

const uint32_t Picture_192[] PROGMEM = 
{
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2,
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, 
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, 
  STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2, STOP_ACTIVE_COLOR2,
};

//BACKGROUND
const uint32_t Picture_193[] PROGMEM = 
{
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, 
  TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND, TURN_BACKGROUND,
};
